### PR TITLE
Add artist name to albums

### PR DESCRIPTION
**Pull request by koteezy**

### CODE REVIEW

**Comment by koteezy** [comment]
In albums like [this](https://itunes.apple.com/ru/album/the-music-of-grand-theft-auto-v/712610834), a lot of artists, and artistId comes back wrong (it's not searched), just like the name. Should we make some kind of check, or attribute, in order to understand that this artistId should not be used?

**Comment by DariusIII** [comment]
Checking for stuff like that should be part of the code.

**Comment by DariusIII** [comment]
Could you add tests, so we have proper workflow?

**Comment by koteezy** [comment]
> Could you add tests, so we have proper workflow?

For ArtistName? Yes, I can. Today I will try to add.

**Comment by koteezy** [comment]
> Could you add tests, so we have proper workflow?

I'm not sure which scenarios to add tests for.. Can you prompt me?

**Comment by DariusIII** [comment]
Test for artist in album, this PR you made.

**Comment by koteezy** [comment]
Um.. on the local machine, the test works as needed.

**Comment by DariusIII** [comment]
> Um.. on the local machine, the test works as needed.

Did you update your fork with changes from this repo? I have added cicrleci config that you are missing, hence the test is failing.

**Comment by DariusIII** [comment]
I'll merge it anyway.

**Comment by koteezy** [comment]
> > Um.. on the local machine, the test works as needed.
> 
> Did you update your fork with changes from this repo? I have added cicrleci config that you are missing, hence the test is failing.

Oh, no. I didn't update the fork.

**Pull request merged**
