### PR TITLE
Fix errors being thrown because longDescription does not exist

### PR DESCRIPTION
**Pull request by ghost**
```
Undefined property: stdClass::$longDescription
at vendor/dariusiii/php-itunes-api/src/Mappers/MovieMapper.php:40
```

### CODE REVIEW

**Review by DariusIII — CHANGES_REQUESTED** [review]
Align the code properly and i will merge it.

**Comment by ghost** [comment]
Done

**Review by DariusIII — APPROVED** [review]

**Comment by ghost** [comment]
Will this tag a new version on Packagist?

**Comment by DariusIII** [comment]
I have pushed a new version with this fix.

https://github.com/DariusIII/php-itunes-api/releases/tag/v1.0.11

**Pull request merged**
